#spring:
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost;database=online_exhibition;encrypt=false
#    username: sa
#    password: password
#  jpa:
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
#    hibernate:
#      ddl-auto: update